### ISSUE TITLE
CDDLib in Julia 1.0

### ISSUE THREAD

**Issue by BotYue** [blegat/HybridSystems.jl#16]
I attempted to run some given examples in Julia 1.0. However, I have some issues with CDDLib. Is there any alternative way to run your example without CDDLib (for example, thermostat.ipynb)? 

In addition, may I ask how to generate a trajectory using this HybridSystem package? Thank you.

```
julia> using CDDLib
[ Info: Precompiling CDDLib [3391f64e-dcde-5f30-b752-e11513730f60]
ERROR: LoadError: CDDLib not properly installed. Please run Pkg.build("CDDLib")
```

**Comment by mforets** [comment]
Have you tried to `Pkg.build("CDDLib")`?  Maybe you have some outdated package? They can be checked with `] status`? The `thermostat.ipynb` example given in this repository works verbatim in my machine (julia v0.7).

> Is there any alternative way to run your example without CDDLib?

Instead of CDDLib you can use eg. Polyhedra's default library, only change this line:

```julia
lib = Polyhedra.IntervalLibrary{Float64}()
```

> In addition, may I ask how to generate a trajectory using this HybridSystem package?

I'm not aware of trajectory generation using this package (if it exists i'd love to know!). In [Reachability.jl](https://github.com/JuliaReach/Reachability.jl
) we do have working algorithms that do flowpipe construction of hybrid systems built with `HybridSystems.jl`. For trajectories see also (this issue)[https://github.com/JuliaReach/Reachability.jl/issues/232].

**Comment by BotYue** [comment]
` ] build CDDLib ` works. Thank you.
